config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'


get '/help', to: 'static_pages#help'

get '/about', to: 'static_pages#about'

get '/admission', to: 'static_pages#admission'

get '/lab', to: 'static_pages#Lab'

get '/tuition_fees', to: 'static_pages#tuition_fees'

get '/contact', to: 'static_pages#contact'

get '/login', to: 'static_pages#login'

get '/academic', to: 'static_pages#academic'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception

def hello

render html: "hello, world!"
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

<small>
ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์ มหาวิทยาลัยเกษตรศาสตร์ (วิทยาเขตบางเขน)
เลขที่ 50 ถนนงามวงศ์วาน แขวงลาดยาว
เขตจตุจักร กรุงเทพ ฯ 10900
โทร. 0-2797-0999 ต่อ 1403-04 1450

</small>

<nav>

<ul>


</ul>

</nav>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

    <title>
        <%= yield(:title) %>
    </title>

    <%= csrf_meta_tags %>

        <%= stylesheet_link_tag 'application', media: 'all',

'data-turbolinks-track': 'reload' %>

            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

                <!--[if lt IE 9]>

<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">

</script>

<![endif]-->

</head>

<body>

    <!--<header class="navbar navbar-fixed-top navbar-inverse">-->
    <header>

        <div class="container">

            <%= link_to image_tag("logo.jpg", alt: "cpe ku logo"),
'https://sample-app-winchawakorn.c9users.io/' %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
</head>
 
<div id="wrapper">

     
    <!--<div id="Search"></div>-->
     
    <form name="message" action="">
        <input name="usermsg" type="text" id="usermsg" size="63" />
        <!--<input name="submitmsg" type="submit"  id="submitmsg" value="Search" />-->
        <%= link_to "Search", root_path %>
    </form>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
<script type="text/javascript">
// jQuery Document
$(document).ready(function(){
 
});
</script>
</body>
</html>

                <nav>

                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <%= link_to "Home", root_path %>
                        </li>

                        <li>
                            <%= link_to "About", about_path %>
                        </li>


                        <li>
                            <%= link_to "Admissions", admission_path%>
                        </li>

                        <li>
                            <%= link_to "Tuition and Scholarships", tuition_fees_path%>
                        </li>

                        <li>
                            <%= link_to "Academics", academic_path%>
                        </li>

                        <li>
                            <%= link_to "Research", lab_path%>
                        </li>


                        <li>
                            <%= link_to "Contact us", contact_path%>
                        </li>
                        
                        <li>
                            <%= link_to "Log in", login_path%>
                        </li>

                    </ul>

                </nav>

        </div>

    </header>

    <div class="container">

        <%= yield %>
            <%= render 'layouts/footer' %>

    </div>

</body>

</html>

app/views/static_pages/Lab.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Research Areas and Labs</title>
    <style media="screen" >
        p{
            font-size: 12
       }
        h2,h3,h4,h5,h6,h7{
          line-height:0.7em
        }
        h2,h3,h4,h5,h6,h7{
        font-size: 20
        }

    </style>
</head>

<body bgcolor="#fffda0">
    <h1> Research Areas and Labs </h1>
    <hr>
    <h2>Cluster #1: Digital and Embedded Systems</h2>
    <p>
        <li>Advance Digital Application (ADA) <br>
            <li>
                Robotics and Intelligent Mechatronics Lab (RIML)
    </p>

    <h2>Cluster #2: Computer Networks and Systems</h2>
    <p>
        <li>Intelligent Wireless Network Group (IWING)
            <li>
                Applied Network Research Lab (ANRES)
                <li>
                    High Performance Computing and Networking Center (HPCNC)
                    <li>
                        Performance and Reliability Lab (PERF) </p>


    <h2>Cluster #3: Info. Engineering and Intelligent Systems</h2>
    <p>
        <li>Data Analysis and Knowledge Discovery Laboratory (DAKDL)
            <li>
                Massive Information and Knowledge Engineering Laboratory (MIKE)
                <li>
                    Specialty Research Unit in Natural Language Processing and Intelligent Information System Technology (NAIST)
                    <li>
                        Smart Home Network System and Service Interaction Laboratory (SHNS) </p>


    <h2>Cluster #4: Software and Database Technology</h2>
    <p>
        <li> Software Engineering and Architecture Laboratory (SEAL)
            <li>
                Database and Software Technology Research Laboratory (DSTRL)
                <li>
                    Innovation and Knowledge Management (IKM)</p>


    <h2>Cluster #5: Graphics and Multimedia</h2>
    <p>
        <li>Multimedia Analysis and Discovery Laboratory ( MAD )</p>


    <h2>Cluster #6: Computer Theory</h2>
    <p>
        <li>Theory Research Lab (theory)
    </p>
    <hr>

</body>

</html>

app/views/static_pages/about.htm.erb
<p>Our Department of Computer Engineering in the Faculty of Engineering, Kasetsart University, was founded on February 3rd, 1989 with the mission to teach, research, develop and service in related areas such that our graduates will meet the market need in Thailand as well as the region. Currently, the department is offering degrees in computer engineering, information technology, software engineering and knowledge engineering as follow:
</p><p><ul>
<li>Bachelor of Engineering in Computer Engineering</li>
<li>Bachelor of Engineering in Software and Knowledge Engineering</li>
<li>Master of Science in Information Technology</li>
<li>Master of Engineering in Computer Engineering</li>
<li>Doctor of Engineering in Computer Engineering</li>
</ul>
In addition to our course offerings, many research units have been founded by faculty members in our department, ranging from development centers and specific research centers to research laboratories. These units are either under the umbrella of the university, the faculty or our department. This leads to the cooperation in research within the university as well as institutions inside and outside the country. Most of our researches have funding from the university, the Royal Thai government, foreign governments and several companies both inside and outside the country.</br>
</p>
<p>

Our department encourages our students, staffs, researchers and faculty members to continuously and repeatedly advance the knowledge in the area. We support our members in several ways from participating in academic training, publishing papers in conferences and seeking cooperation with experts in related area worldwide.</br>
</p>
<p>

Our vision is to continuously take a lead role in education, training and research in computer engineering to make our graduates fully prepared and ready for the rapidly growing industry in Thailand as well as the region.

 </p>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
<p>Our Department of Computer Engineering in the Faculty of Engineering, Kasetsart University, was founded on February 3rd, 1989 with the mission to teach, research, develop and service in related areas such that our graduates will meet the market need in Thailand as well as the region. Currently, the department is offering degrees in computer engineering, information technology, software engineering and knowledge engineering as follow:
</p><p><ul>
<li>Bachelor of Engineering in Computer Engineering</li>
<li>Bachelor of Engineering in Software and Knowledge Engineering</li>
<li>Master of Science in Information Technology</li>
<li>Master of Engineering in Computer Engineering</li>
<li>Doctor of Engineering in Computer Engineering</li>
</ul>
In addition to our course offerings, many research units have been founded by faculty members in our department, ranging from development centers and specific research centers to research laboratories. These units are either under the umbrella of the university, the faculty or our department. This leads to the cooperation in research within the university as well as institutions inside and outside the country. Most of our researches have funding from the university, the Royal Thai government, foreign governments and several companies both inside and outside the country.</br>
</p>
<p>

Our department encourages our students, staffs, researchers and faculty members to continuously and repeatedly advance the knowledge in the area. We support our members in several ways from participating in academic training, publishing papers in conferences and seeking cooperation with experts in related area worldwide.</br>
</p>
<p>

Our vision is to continuously take a lead role in education, training and research in computer engineering to make our graduates fully prepared and ready for the rapidly growing industry in Thailand as well as the region.

 </p>
</html>

app/views/static_pages/academic.html.erb
<h3>
  Academics<br></br>
</h3>
<p>
ภาควิชาฯ ได้เปิดหลักสูตรเพื่อสนองความต้องการของประเทศจำนวน 5 หลักสูตร แบ่งเป็นหลักสูตรระดับปริญญาตรี 1 หลักสูตร หลักสูตรนานาชาติระดับปริญญาตรี 1 หลักสูตร หลักสูตรระดับปริญญาโท 2 หลักสูตร และหลักสูตรระดับปริญญาเอก 1 หลักสูตร คือ
</br></br>
หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์</br>
หลักสูตรวิศวกรรมศาสตรบัณฑิตนานาชาติ สาขาวิศวกรรมซอฟต์แวร์และความรู้</br>
หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาเทคโนโลยีสารสนเทศ</br>
หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์</br>
หลักสูตรวิศวกรรมศาสตรดุษฎีบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์</br>
นอกจากนี้ภาควิชาฯ ยังให้ความร่วมมือในการสอนรายวิชาหลัก รายวิชารอง และรายวิชาเลือก ที่อยู่ในความชำนาญของภาควิชาฯ ดังได้กล่าวข้างต้น ให้แก่หลักสูตรอื่นๆ ทั้งที่เป็นของภาควิชาฯ ภายใต้คณะวิศวกรรมศาสตร์ ภาควิชาต่างคณะ และภาควิชาในต่างวิทยาเขต
</p>

app/views/static_pages/admission.html.erb
<!DOCTYPE html>
<html>
<p>
    This is admission score for the past year of Computer Engineering
    
</p><p></br>
<%= link_to image_tag("admission.jpg", alt: "cpe ku score"),
'https://sample-app-winchawakorn.c9users.io/' %>
</p>
<p></br>
    This is admission score for the past year of Software Engineering
</p><br/>
<%= link_to image_tag("skescore.jpg", alt: "cpe ku score"),
'https://sample-app-winchawakorn.c9users.io/' %>
</br>
</html>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Contact Us</title>
    <style>
        #map {
            height: 400px;
            width: 100%;
        }
    </style>
</head>

<body>
    <h3>Contact Us</h3>
    <hr>
    <p>
        ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์ มหาวิทยาลัยเกษตรศาสตร์ (วิทยาเขตบางเขน)
        <br>เลขที่ 50 ถนนงามวงศ์วาน แขวงลาดยาว <br>เขตจตุจักร กรุงเทพ ฯ 10900 <br>โทร. 0-2797-0999 ต่อ 1403-04 1450 </p>
    <div id="map"></div>
    <script>
        function initMap() {
            var uluru = {
                lat: 13.846180,
                lng: 100.568601
            };
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 16,
                center: uluru
            });
            var marker = new google.maps.Marker({
                position: uluru,
                map: map
            });
        }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAshUO8CsZpobKyc00jGENkNgzlJfsaiGY&callback=initMap">
    </script>
    <hr>
</body>

</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">

<h1>Computer engineering KU</h1>

<h2>

text

</h2>

</div>

app/views/static_pages/login.html.erb
<% provide(:title, "Log in") %>
<div class = "row">
<div class = "col-md-6 col-md-offset-3">
<h1>Log in</h1>
<br><br>
<p>Email</p><input size = "50"></input><br><br>
<p>Password</p><input size = "50" type = "password"></input><br><br>
<%= link_to "Login", '#', class: "btn btn-lg btn-primary" %> or <%= link_to "Sign up", root_path %>
</div>
</div>

app/views/static_pages/tuition_fees.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        Admissions
    </title>
</head>

<body bgcolor="#fffda0">
    <h2> Tuition Fee </h2>
    <p>
        60,700 Baht per semester.(for Thai Student) <br> 70,700 Baht per semester.(for International Student)
    </P>
    <h2> Scholarships </h2>
    <p>
        1. Excellent Student Scholarships <br>
        2. Internship Abroad Scholarships <br>
        3. Student Exchange Scholarships <br>
        4. AEC Student Exchange Scholarships <br>
        5. Scholarships from our partners e.g., <a href="http://www.triumphmotorcycles.com">Triumph Motorcycles, Thailand (http://www.triumphmotorcycles.com)</a> <br> <br>
        More Information (iup@ku.ac.th)
    </p>
</body>

</html>